//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIYFE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
            this.ArticleResources = new HashSet<ArticleResource>();
            this.ArticleStatus = new HashSet<ArticleStatus>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ArticleId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int ArticleTypeId { get; set; }
        public int CategoryRowId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Keywords { get; set; }
        public string MainContent { get; set; }
        public string SideContent { get; set; }
        public string ListItemContent { get; set; }
        public int ViewRequests { get; set; }
        public string URLLink { get; set; }
        public string PreviewImg { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        public virtual ICollection<ArticleResource> ArticleResources { get; set; }
        public virtual ICollection<ArticleStatus> ArticleStatus { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Category Category { get; set; }
    }
}
