//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIYFE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleStatu
    {
        public int ArticleStatusRowId { get; set; }
        public int ArticleId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual StatusType StatusType { get; set; }
    }
}
