//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIYFE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int CategoryRowId { get; set; }
        public int TopNavIndex { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SecondLevCategoryId { get; set; }
        public Nullable<int> ThirdLevCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryUrl { get; set; }
        public string SecondLevCategoryName { get; set; }
        public string SecondLevCategoryUrl { get; set; }
        public string ThirdLevCategoryName { get; set; }
        public string ThirdLevCategoryUrl { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
