//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIYFE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeSeasons = new HashSet<RecipeSeason>();
            this.RecipeDays = new HashSet<RecipeDay>();
            this.RecipeIngredients = new HashSet<RecipeIngredient>();
        }
    
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public string Instructions { get; set; }
        public int UseAmount { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<RecipeSeason> RecipeSeasons { get; set; }
        public virtual ICollection<RecipeDay> RecipeDays { get; set; }
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
    }
}
