//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIYFE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int EmailRowId { get; set; }
        public string Email1 { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
