//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIYFE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDay
    {
        public int RecipeDayId { get; set; }
        public int DayId { get; set; }
        public int RecipeId { get; set; }
        public bool Active { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
